language: node_js
node_js:
  - "node"
sudo: false
dist: trusty

cache:
  directories:
    - "node_modules"

branches:
 only:
 - master

install:
  - npm i
  - npm run build

script:
  - ./scripts/deploy.sh

notifications:
  email: false
