export const key = {
    'B': 'Beginners Meeting',
    'BK': 'Book Study',
    'C': 'Closed Meeting for Addicts Only',
    'CL': 'Candlelight',
    'CW': 'Children Welcome/Child Care',
    'D': 'Discussion',
    'M': 'Men Only',
    'ME': 'Meditation',
    'O': 'Open Meeting all are welcome',
    'RF': 'Rotating Format',
    'SD': 'Speaker/Discussion',
    'SG': 'Step Working Guide',
    'So': 'Speaker Only',
    'St': 'Step',
    'SW': 'Step Writing',
    'Tr': 'Tradition',
    'W': 'Women only',
    'WC': 'Wheelchair Accessible',
    'YP': 'Young People',
}
