const prices = {
  books: [
    { name: "6th Edition Basic Text (Hardcover)", itemNumber: "1101", price: 12.15, quantity: 0, subTotal: 0 },
    { name: "6th Edition Basic Text (Softcover)", itemNumber: "1102", price: 12.15, quantity: 0, subTotal: 0 },
    { name: "6th Edition Basic Text (Pocket-sized)", itemNumber: "1106", price: 12.15, quantity: 0, subTotal: 0 },
    { name: "Just for Today (Softcover)", itemNumber: "1112", price: 9.55, quantity: 0, subTotal: 0 },
    { name: "Just for Today (Pocket-Sized)", itemNumber: "1113", price: 9.85, quantity: 0, subTotal: 0 },
    { name: "Miracles Happen/CD (Softcover)", itemNumber: "1121", price: 11.65, quantity: 0, subTotal: 0 },
    { name: "It Works: How & Why (Hardcover)", itemNumber: "1140", price: 9.55, quantity: 0, subTotal: 0 },
    { name: "It Works: How & Why (Softcover)", itemNumber: "1143", price: 9.55, quantity: 0, subTotal: 0 },
    { name: "It Works: How & Why (Pocket-Sized)", itemNumber: "1144", price: 9.85, quantity: 0, subTotal: 0 },
    { name: "Sponsorship (Softcover Only)", itemNumber: "1130", price: 8.75, quantity: 0, subTotal: 0 },
    { name: "Living Clean: The Journey Continues (Hardcover)", itemNumber: "1150", price: 10.35, quantity: 0, subTotal: 0 },
    { name: "Living Clean: The Journey Continues (Softcover)", itemNumber: "1151", price: 10.35, quantity: 0, subTotal: 0 },
    { name: "Introductory Guide to NA, Revised", itemNumber: "1200", price: 2.15, quantity: 0, subTotal: 0 },
    { name: "Guiding Principles The Twelve Traditions (Hardcover)", itemNumber: "1201", price: 11.65, quantity: 0, subTotal: 0 },
    { name: "Guiding Principles The Twelve Traditions (Soft Cover)", itemNumber: "1202", price: 11.65, quantity: 0, subTotal: 0 },
    { name: "The NA Step Working Guides", itemNumber: "1400", price: 9, quantity: 0, subTotal: 0 },
  ],
  booklets: [
    { name: "Twelve Concepts for NA Service", itemNumber: "1164", price: 2.2, quantity: 0, subTotal: 0 },
    { name: "White Booklet (no staples)", itemNumber: "1500HnI", price: 0.8, quantity: 0, subTotal: 0 },
    { name: "In Times of Illness", itemNumber: "1603", price: 3.4, quantity: 0, subTotal: 0 },
    { name: "The Group Booklet (Revised)", itemNumber: "1600", price: 1, quantity: 0, subTotal: 0 },
    { name: "Behind the Walls, (no staples)", itemNumber: "1601HnI", price: 1, quantity: 0, subTotal: 0 },
    { name: "IP# 10 Working Step Four", itemNumber: "3110", price: 0.82, quantity: 0, subTotal: 0 },
    { name: "NA: A Resource in Your Community", itemNumber: "1604", price: 0.42, quantity: 0, subTotal: 0 },
  ],
  informationPamphlets: [
    { name: "IP# 1 Who, What, How, and Why", itemNumber: "3101", price: 0.25, quantity: 0, subTotal: 0 },
    { name: "IP# 2 The Group", itemNumber: "3102", price: 0.33, quantity: 0, subTotal: 0 },
    { name: "IP# 5 Another Look", itemNumber: "3105", price: 0.25, quantity: 0, subTotal: 0 },
    { name: "IP# 6 Recovery and Relapse", itemNumber: "3106", price: 0.25, quantity: 0, subTotal: 0 },
    { name: "IP# 7 Am I an Addict?", itemNumber: "3107", price: 0.25, quantity: 0, subTotal: 0 },
    { name: "IP# 8 Just for Today", itemNumber: "3108", price: 0.25, quantity: 0, subTotal: 0 },
    { name: "IP# 9 Living the Program", itemNumber: "3109", price: 0.25, quantity: 0, subTotal: 0 },
    { name: "IP# 11 Sponsorship, Revised", itemNumber: "3111", price: 0.25, quantity: 0, subTotal: 0 },
    { name: "IP# 12 The Triangle of Self-Obsession", itemNumber: "3112", price: 0.25, quantity: 0, subTotal: 0 },
    { name: "IP# 13 By Young Addicts, For Young Addicts", itemNumber: "3113", price: 0.33, quantity: 0, subTotal: 0 },
    { name: "IP# 14 One Addict's Experience with Acceptance, Faith, and Commitment", itemNumber: "3114", price: 0.25, quantity: 0, subTotal: 0 },
    { name: "IP# 15 Public Information and the NA Member", itemNumber: "3115", price: 0.25, quantity: 0, subTotal: 0 },
    { name: "IP# 16 For the Newcomer", itemNumber: "3116", price: 0.25, quantity: 0, subTotal: 0 },
    { name: "IP# 17 For Those in Treatment", itemNumber: "3117", price: 0.33, quantity: 0, subTotal: 0 },
    { name: "IP# 19 Self-Acceptance", itemNumber: "3119", price: 0.25, quantity: 0, subTotal: 0 },
    { name: "IP# 20 Hospitals & Institutions Service and the NA Member", itemNumber: "3120", price: 0.25, quantity: 0, subTotal: 0 },
    { name: "IP# 21 The Loner: Staying Clean in Isolation", itemNumber: "3121", price: 0.33, quantity: 0, subTotal: 0 },
    { name: "IP# 22 Welcome to Narcotics Anonymous", itemNumber: "3122", price: 0.25, quantity: 0, subTotal: 0 },
    { name: "IP# 23 Staying Clean on the Outside", itemNumber: "3123", price: 0.25, quantity: 0, subTotal: 0 },
    { name: "IP# 24 Money Matters: Self-Support in NA", itemNumber: "3124", price: 0.56, quantity: 0, subTotal: 0 },
    { name: "IP# 26 Accessibility for Those with Additional Needs", itemNumber: "3126", price: 0.25, quantity: 0, subTotal: 0 },
    { name: "IP# 27 For the Parents or Guardians of Young People in NA", itemNumber: "3127", price: 0.33, quantity: 0, subTotal: 0 },
    { name: "IP# 28 Funding NA Service", itemNumber: "3128", price: 0.37, quantity: 0, subTotal: 0 },
    { name: "IP# 29 Introduction to NA Meetings", itemNumber: "3129", price: 0.25, quantity: 0, subTotal: 0 },
    { name: "IP #30 Mental Health in Recovery", itemNumber: "3130", price: 0.33, quantity: 0, subTotal: 0 },

  ],
  serviceProducts: [
    { name: "H&I Handbook w/CD", itemNumber: "2101", price: 10.25, quantity: 0, subTotal: 0 },
    { name: "H&I Basics", itemNumber: "2101G", price: 0.65, quantity: 0, subTotal: 0 },
    { name: "Public Relations Handbook", itemNumber: "2102", price: 10.45, quantity: 0, subTotal: 0 },
    { name: "PR Basics", itemNumber: "2102B", price: 1.85, quantity: 0, subTotal: 0 },
    { name: "A Guide to World Services in NA", itemNumber: "2104", price: 4.55, quantity: 0, subTotal: 0 },
    { name: "Literature Committee Handbook", itemNumber: "2105", price: 2.9, quantity: 0, subTotal: 0 },
    { name: "Handbook for NA Newsletters", itemNumber: "2106", price: 2.25, quantity: 0, subTotal: 0 },
    { name: "A Guide to Phoneline Service", itemNumber: "2107", price: 3.8, quantity: 0, subTotal: 0 },
    { name: "Treasurer's Handbook (Revised)", itemNumber: "2109", price: 2.25, quantity: 0, subTotal: 0 },
    { name: "Group Treasurer's Workbook (Revised)", itemNumber: "2110", price: 2.25, quantity: 0, subTotal: 0 },
    { name: "Group Treasurer's Record Pad (records for 13 months)", itemNumber: "9001", price: 0.8, quantity: 0, subTotal: 0 },
    { name: "A Guide to Local Services in NA", itemNumber: "2111", price: 7.5, quantity: 0, subTotal: 0 },
    { name: "Outreach Resource Information", itemNumber: "2113", price: 2.9, quantity: 0, subTotal: 0 },
    { name: "Additional Needs Resource Information", itemNumber: "2114", price: 2.9, quantity: 0, subTotal: 0 },
    { name: "Institutional Group Guide", itemNumber: "2115", price: 4.55, quantity: 0, subTotal: 0 },
    { name: "Planning Basics", itemNumber: "2116", price: 2.2, quantity: 0, subTotal: 0 },
    { name: "Group Business Meetings", itemNumber: "2202", price: 0.25, quantity: 0, subTotal: 0 },
    { name: "Group Trusted Servants: Roles & Responsibilities", itemNumber: "2203", price: 0.25, quantity: 0, subTotal: 0 },
    { name: "Disruptive and Violent Behavior", itemNumber: "2204", price: 0.25, quantity: 0, subTotal: 0 },
    { name: "NA Groups & Medication", itemNumber: "2205", price: 0.33, quantity: 0, subTotal: 0 },
    { name: "Principles and Leadership in NA Service", itemNumber: "2206", price: 0.33, quantity: 0, subTotal: 0 },
    { name: "Social Media and Our Guiding Principles", itemNumber: "2207", price: 0.33, quantity: 0, subTotal: 0 },
    { name: "Persons Receiving Medication -Assisted Treatment", itemNumber: "2306", price: 0.32, quantity: 0, subTotal: 0 },
  ],
  keyTags: [
    { name: "White - Welcome Keytag", itemNumber: "4100", price: 0.56, quantity: 0, subTotal: 0 },
    { name: "Orange - 30 Day Keytag", itemNumber: "4101", price: 0.56, quantity: 0, subTotal: 0 },
    { name: "Green - 60 Day Keytag", itemNumber: "4102", price: 0.56, quantity: 0, subTotal: 0 },
    { name: "Red - 90 Day Keytag", itemNumber: "4103", price: 0.56, quantity: 0, subTotal: 0 },
    { name: "Blue - 6 Month Keytag", itemNumber: "4104", price: 0.56, quantity: 0, subTotal: 0 },
    { name: "Yellow - 9 Month Keytag", itemNumber: "4105", price: 0.56, quantity: 0, subTotal: 0 },
    { name: "Moonglow - 1 Year Keytag", itemNumber: "4106", price: 0.56, quantity: 0, subTotal: 0 },
    { name: "Grey - 18 Month Keytag", itemNumber: "4107", price: 0.56, quantity: 0, subTotal: 0 },
    { name: "Black - Multiple Year Keytag", itemNumber: "4108", price: 0.56, quantity: 0, subTotal: 0 },
  ],
  largePrint: [
    { name: "Large Print White booklet", itemNumber: "1500LP", price: 0.8, quantity: 0, subTotal: 0 },
    { name: "Large Print 6th Edition Basic Text", itemNumber: "1101LP", price: 16.55, quantity: 0, subTotal: 0 },
    { name: "Large Print It Works", itemNumber: "1140LP", price: 13.5, quantity: 0, subTotal: 0 },
  ],
  medallions: [
    { name: "Bronze Medallion 18 Months", itemNumber: "4300", price: 3.4, quantity: 0, subTotal: 0 },
    { name: "Bronze Medallion 1 Year(s)", itemNumber: "4301", price: 3.4, quantity: 0, subTotal: 0 },
    { name: "Bronze Medallion 2 Year(s)", itemNumber: "4302", price: 3.4, quantity: 0, subTotal: 0 },
    { name: "Bronze Medallion 3 Year(s)", itemNumber: "4303", price: 3.4, quantity: 0, subTotal: 0 },
    { name: "Bronze Medallion 4 Year(s)", itemNumber: "4304", price: 3.4, quantity: 0, subTotal: 0 },
    { name: "Bronze Medallion 5 Year(s)", itemNumber: "4305", price: 3.4, quantity: 0, subTotal: 0 },
    { name: "Bronze Medallion 6 Year(s)", itemNumber: "4306", price: 3.4, quantity: 0, subTotal: 0 },
    { name: "Bronze Medallion 7 Year(s)", itemNumber: "4307", price: 3.4, quantity: 0, subTotal: 0 },
    { name: "Bronze Medallion 8 Year(s)", itemNumber: "4308", price: 3.4, quantity: 0, subTotal: 0 },
    { name: "Bronze Medallion 9 Year(s)", itemNumber: "4309", price: 3.4, quantity: 0, subTotal: 0 },
    { name: "Bronze Medallion 10 Year(s)", itemNumber: "4310", price: 3.4, quantity: 0, subTotal: 0 },
    { name: "Bronze Medallion 11 Year(s)", itemNumber: "4311", price: 3.4, quantity: 0, subTotal: 0 },
    { name: "Bronze Medallion 12 Year(s)", itemNumber: "4312", price: 3.4, quantity: 0, subTotal: 0 },
    { name: "Bronze Medallion 13 Year(s)", itemNumber: "4313", price: 3.4, quantity: 0, subTotal: 0 },
    { name: "Bronze Medallion 14 Year(s)", itemNumber: "4314", price: 3.4, quantity: 0, subTotal: 0 },
    { name: "Bronze Medallion 15 Year(s)", itemNumber: "4315", price: 3.4, quantity: 0, subTotal: 0 },
    { name: "Bronze Medallion 16 Year(s)", itemNumber: "4316", price: 3.4, quantity: 0, subTotal: 0 },
    { name: "Bronze Medallion 17 Year(s)", itemNumber: "4317", price: 3.4, quantity: 0, subTotal: 0 },
    { name: "Bronze Medallion 18 Year(s)", itemNumber: "4318", price: 3.4, quantity: 0, subTotal: 0 },
    { name: "Bronze Medallion 19 Year(s)", itemNumber: "4319", price: 3.4, quantity: 0, subTotal: 0 },
    { name: "Bronze Medallion 20 Year(s)", itemNumber: "4320", price: 3.4, quantity: 0, subTotal: 0 },
    { name: "Bronze Medallion 21 Year(s)", itemNumber: "4321", price: 3.4, quantity: 0, subTotal: 0 },
    { name: "Bronze Medallion 22 Year(s)", itemNumber: "4322", price: 3.4, quantity: 0, subTotal: 0 },
    { name: "Bronze Medallion 23 Year(s)", itemNumber: "4323", price: 3.4, quantity: 0, subTotal: 0 },
    { name: "Bronze Medallion 24 Year(s)", itemNumber: "4324", price: 3.4, quantity: 0, subTotal: 0 },
    { name: "Bronze Medallion 25 Year(s)", itemNumber: "4325", price: 3.4, quantity: 0, subTotal: 0 },
    { name: "Bronze Medallion 26 Year(s)", itemNumber: "4326", price: 3.4, quantity: 0, subTotal: 0 },
    { name: "Bronze Medallion 27 Year(s)", itemNumber: "4327", price: 3.4, quantity: 0, subTotal: 0 },
    { name: "Bronze Medallion 28 Year(s)", itemNumber: "4328", price: 3.4, quantity: 0, subTotal: 0 },
    { name: "Bronze Medallion 29 Year(s)", itemNumber: "4329", price: 3.4, quantity: 0, subTotal: 0 },
    { name: "Bronze Medallion 30 Year(s)", itemNumber: "4330", price: 3.4, quantity: 0, subTotal: 0 },
    { name: "Bronze Medallion 31 Year(s)", itemNumber: "4331", price: 3.4, quantity: 0, subTotal: 0 },
    { name: "Bronze Medallion 32 Year(s)", itemNumber: "4332", price: 3.4, quantity: 0, subTotal: 0 },
    { name: "Bronze Medallion 33 Year(s)", itemNumber: "4333", price: 3.4, quantity: 0, subTotal: 0 },
    { name: "Bronze Medallion 34 Year(s)", itemNumber: "4334", price: 3.4, quantity: 0, subTotal: 0 },
    { name: "Bronze Medallion 35 Year(s)", itemNumber: "4335", price: 3.4, quantity: 0, subTotal: 0 },
    { name: "Bronze Medallion 36 Year(s)", itemNumber: "4336", price: 3.4, quantity: 0, subTotal: 0 },
    { name: "Bronze Medallion 37 Year(s)", itemNumber: "4337", price: 3.4, quantity: 0, subTotal: 0 },
    { name: "Bronze Medallion 38 Year(s)", itemNumber: "4338", price: 3.4, quantity: 0, subTotal: 0 },
    { name: "Bronze Medallion 39 Year(s)", itemNumber: "4339", price: 3.4, quantity: 0, subTotal: 0 },
    { name: "Bronze Medallion 40 Year(s)", itemNumber: "4340", price: 3.4, quantity: 0, subTotal: 0 },
    { name: "Bronze Medallion 41 Year(s)", itemNumber: "4341", price: 3.4, quantity: 0, subTotal: 0 },
    { name: "Bronze Medallion 42 Year(s)", itemNumber: "4342", price: 3.4, quantity: 0, subTotal: 0 },
    { name: "Bronze Medallion 43 Year(s)", itemNumber: "4343", price: 3.4, quantity: 0, subTotal: 0 },
    { name: "Bronze Medallion 44 Year(s)", itemNumber: "4344", price: 3.4, quantity: 0, subTotal: 0 },
    { name: "Bronze Medallion 45 Year(s)", itemNumber: "4345", price: 3.4, quantity: 0, subTotal: 0 },
    { name: "Bronze Medallion 46 Year(s)", itemNumber: "4346", price: 3.4, quantity: 0, subTotal: 0 },
    { name: "Bronze Medallion 47 Year(s)", itemNumber: "4347", price: 3.4, quantity: 0, subTotal: 0 },
    { name: "Bronze Medallion 48 Year(s)", itemNumber: "4348", price: 3.4, quantity: 0, subTotal: 0 },
    { name: "Bronze Medallion 49 Year(s)", itemNumber: "4349", price: 3.4, quantity: 0, subTotal: 0 },
    { name: "Bronze Medallion 50 Year(s)", itemNumber: "4350", price: 3.4, quantity: 0, subTotal: 0 },
    { name: "Bronze Medallion 51 Year(s)", itemNumber: "4351", price: 3.4, quantity: 0, subTotal: 0 },
    { name: "Bronze Medallion 52 Year(s)", itemNumber: "4352", price: 3.4, quantity: 0, subTotal: 0 },
    { name: "Bronze Medallion 53 Year(s)", itemNumber: "4353", price: 3.4, quantity: 0, subTotal: 0 },
    { name: "Bronze Medallion 54 Year(s)", itemNumber: "4354", price: 3.4, quantity: 0, subTotal: 0 },
    { name: "Bronze Medallion 55 Year(s)", itemNumber: "4355", price: 3.4, quantity: 0, subTotal: 0 },
    { name: "Eternity", itemNumber: "4399", price: 3.4, quantity: 0, subTotal: 0 },
  ],
  specialtyItems: [
    { name: "Group Starter Kit", itemNumber: "9020", price: 7.2, quantity: 0, subTotal: 0 },
    { name: "Group Reading Placard Set", itemNumber: "9130", price: 4.9, quantity: 0, subTotal: 0 },
    { name: "Literature rack (wire, 8-pocket)", itemNumber: "9053", price: 22.05, quantity: 0, subTotal: 0 },
    { name: "Literature rack (wire, 16-pocket)", itemNumber: "9054", price: 27.7, quantity: 0, subTotal: 0 },
    { name: "Literature rack (wire, 20-pocket)", itemNumber: "9055", price: 40.4, quantity: 0, subTotal: 0 },
    { name: "7 Poster Set", itemNumber: "9070", price: 11, quantity: 0, subTotal: 0 },
    { name: "My Gratitude Speaks Poster", itemNumber: "9071", price: 1.55, quantity: 0, subTotal: 0 },
    { name: "Serenity Prayer Poster", itemNumber: "9072", price: 1.55, quantity: 0, subTotal: 0 },
    { name: "Twelve Steps Poster", itemNumber: "9073", price: 3.5, quantity: 0, subTotal: 0 },
    { name: "Twelve Traditions Poster", itemNumber: "9074", price: 3.5, quantity: 0, subTotal: 0 },
    { name: "Third Step Prayer Poster", itemNumber: "9075", price: 1.55, quantity: 0, subTotal: 0 },
    { name: "Just for Today Poster", itemNumber: "9076", price: 1.55, quantity: 0, subTotal: 0 },
    { name: "Twelve Concepts Poster", itemNumber: "9077", price: 3.5, quantity: 0, subTotal: 0 },
    { name: "7th Tradition Box", itemNumber: "9111", price: 3.2, quantity: 0, subTotal: 0 },
  ],
  multimediaProducts: [
    { name: "It Works, audiotape", itemNumber: "8820", price: 19.4, quantity: 0, subTotal: 0 },
  ]
}

export default prices